# Generated by Django 5.0.7 on 2024-07-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_user_is_active_user_is_staff_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_id",
            new_name="id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
    ]
